---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__(<p>__start__</p>)
	security(security)
	auth(auth)
	classify(classify)
	validate(validate)
	operate(operate)
	sms_decision(sms_decision)
	sms_offer(sms_offer)
	sms_send(sms_send)
	continue(continue)
	wait_for_input(wait_for_input)
	end(end)
	__end__(<p>__end__</p>)
	__start__ --> security;
	security -.-> auth;
	security -.-> classify;
	security -. &nbsp;end&nbsp; .-> end;
	auth -.-> classify;
	auth -.-> wait_for_input;
	classify -.-> validate;
	classify -.-> wait_for_input;
	classify -.-> continue;
	validate -.-> operate;
	validate -.-> wait_for_input;
	operate -.-> continue;
	operate -.-> sms_decision;
	sms_decision -.-> sms_offer;
	sms_decision -.-> continue;
	sms_offer -.-> wait_for_input;
	sms_send -.-> continue;
	continue -.-> wait_for_input;
	continue -. &nbsp;end&nbsp; .-> __end__;
	wait_for_input -.-> security;
	wait_for_input -.-> auth;
	wait_for_input -.-> classify;
	wait_for_input -.-> operate;
	wait_for_input -.-> sms_send;
	operate -.-> operate;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc