---
config:
  flowchart:
    curve: linear
---
graph TD;
        __start__(<p>__start__</p>)
        greeting(greeting)
        classify(classify)
        fallback(fallback)
        process_tools(process_tools)
        handle_error(handle_error)
        end(end)
        __end__([<p>__end__</p>]):::last
        __start__ --> greeting;
        end --> __end__;
        greeting -. &nbsp;wait_for_input&nbsp; .-> __end__;
        greeting -.-> __end__;
        classify -.-> fallback;
        classify -.-> process_tools;
        classify -.-> end;
        classify -.-> __end__;
        fallback -.-> handle_error;
        fallback -.-> __end__;
        process_tools -.-> __end__;
        handle_error -.-> __end__;
        classDef default fill:#f2f0ff,line-height:1.2
        classDef first fill-opacity:0
        classDef last fill:#bfb6fc