---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	initial_greeting(initial_greeting)
	security(security)
	auth(auth)
	classify(classify)
	validate(validate)
	operate(operate)
	sms_decision(sms_decision)
	sms_offer(sms_offer)
	sms_send(sms_send)
	continue(continue)
	__end__([<p>__end__</p>]):::last
	__start__ --> initial_greeting;
	auth -.-> classify;
	classify -.-> operate;
	classify -.-> validate;
	continue -. &nbsp;end&nbsp; .-> __end__;
	continue -.-> security;
	initial_greeting --> security;
	operate -.-> continue;
	operate -.-> sms_decision;
	security -. &nbsp;end&nbsp; .-> __end__;
	security -.-> auth;
	security -.-> classify;
	sms_decision -.-> continue;
	sms_decision -.-> sms_offer;
	sms_offer -.-> continue;
	sms_offer -.-> sms_send;
	sms_send -.-> continue;
	validate -.-> classify;
	validate -.-> operate;
	auth -.-> auth;
	classify -.-> classify;
	continue -.-> continue;
	sms_offer -.-> sms_offer;
	validate -.-> validate;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
